kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cloud-native-workspace
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 'latest'
      annotations:
        description: Cloud Native Stack and CodeReady Workspaces
        iconClass: icon-java
        supports: java
        tags: 'builder,java'
        version: 'latest'
      from:
        kind: DockerImage
        name: 'quay.io/openlab-red/cloud-native-workspace:latest'
      importPolicy: {}
      referencePolicy:
        type: Source
